version: '3.4'

networks:
  dev:
    driver: bridge

services:
  catebi_api:
    image: catebi_api:latest
    platform: linux/amd64
    depends_on:
      - catebi_db
    container_name: catebi_api
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ci/docker/Dockerfile.catebi.api
    environment:
      - ConnectionStrings__Pgsql=Host=catebi_db;Port=5432;Database=catebi;Username=catebi_app;Password=password;Include Error Detail=True;
    networks:
      - dev

  catebi_db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - dev

volumes:
  postgres-data:
